### PR TITLE
Fix/preamble

### PR DESCRIPTION
**Pull request by JensHeinrich**
Solves #198

### CODE REVIEW

**Comment by JensHeinrich** [comment]
The broken checks are in code I did't touch and I really don't get it ATM

**Comment by nschloe** [comment]
Do we need the option to drop the preamble?

**Comment by JensHeinrich** [comment]
Same reasoning as the last time: It's the current behaviour

**Comment by nschloe** [comment]
If I understand corrent, if no `@preamble` is present, the behavior is unchanged. If this is the case, we don't need a flag. Or is there a good reason to disable it?

**Comment by JensHeinrich** [comment]
Currently if there are `@preamble` entries they are removed when running `betterbib format` (that's the main reason I created the PR...)

**Comment by nschloe** [comment]
Alright, let's remove `--keep-preamble` and always keep it.

**Comment by JensHeinrich** [comment]
done

**Comment by nschloe** [comment]
Thanks!

**Pull request merged**
