### PR TITLE
for #32 on Windows

### LINKED ISSUE #32: more Python 3 Unicode
The following entry 
```tex
@Article{Cigler2012,
  author  = {Cigler, Ji{\v{r}}{\'{i}} and Pr{\'{i}}vara, Samuel and V{\'{a}\v{n}}a, Zden{\v{e}}k and {\v{Z}}{\'{a}}{\v{c}}ekov{\'{a}}, Eva and Ferkl, Luk{\'{a}}{\v{s}}},
  title   = {Optimization of predicted mean vote index within model predictive control framework: Computationally tractable solution},
  journal = {Energy and Buildings},
  year    = {2012},
  volume  = {52},
  pages   = {39--49},
  doi     = {10.1016/j.enbuild.2012.05.022},
  issn    = {03787788}
}
```

gives the following error:
```
Reading from: refin2.bib
Saving to: refout.bib
|----------| 0/1   0% [elapsed: 00:00 left: ?, ? iters/sec]Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\subprocess.py", line 1170, in _readerthread
    buffer.append(fh.read())
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 176: character maps to <undefined>

Traceback (most recent call last):
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\Scripts\betterbib", line 98, in <module>
    _main()
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\Scripts\betterbib", line 48, in _main
    result = source.find_unique(entry)
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\betterbib\crossref.py", line 148, in find_unique
    payload = latex_to_unicode(' '.join(l)).replace(' ', '+')
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\site-packages\betterbib\bibtex.py", line 15, in latex_to_unicode
    universal_newlines=True
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\subprocess.py", line 609, in check_output
    output, unused_err = process.communicate(inputdata, timeout=timeout)
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\subprocess.py", line 959, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Users\mthorade\Documents\Python\WinPython-64bit-3.4.2.3\python-3.4.2.amd64\lib\subprocess.py", line 1234, in _communicate
    stdout = stdout[0]
IndexError: list index out of range
```

Works in WinPython 2.7.9 on Windows, fails in WinPython 3.4 on Windows.

### PR DESCRIPTION
**Pull request by thorade**
additional fix that closes #32

### CODE REVIEW

**Comment by nschloe** [comment]
This works with Python3 for me, not Python2. Looking at it right now...

**Comment by thorade** [comment]
sorry, i thought the `from io import open` would make it work on Python 2.7+
Or are you on Python 2.6 ?

**Comment by nschloe** [comment]
Nope, 2.7 here. Don't you get
```
Reading from: blechta.bib
Saving to: out.bib

Traceback (most recent call last):
  File "betterbib", line 99, in <module>
    _main()
  File "betterbib", line 35, in _main
    betterbib.__version__
TypeError: write() argument 1 must be unicode, not str
```
as well?

**Comment by thorade** [comment]
Yes, I get the same error. Using unicode(betterbib.__version__) then fixes it for Python 2.7, but breaks it again for Python 3.5

**Comment by nschloe** [comment]
Got it now.

**Pull request merged**
