### PR TITLE
Update tools.py

### PR DESCRIPTION
**Pull request by keithbriggs**
Add more latex encodings of special characters.

### CODE REVIEW

**Comment by nschloe** [comment]
You could have just edited your first PR, but this is okay.

**Comment by keithbriggs** [comment]
How long before this fix becomes available via pip?

**Comment by nschloe** [comment]
You can just install it locally with pip. `pip install .`

**Comment by keithbriggs** [comment]
That gives:

Directory '.' is not installable. File 'setup.py' not found.


________________________________

**Comment by nschloe** [comment]
You need newer versions of pip/setuptools.

**Comment by keithbriggs** [comment]
Thanks - I upgraded pip and it worked.

________________________________

**Pull request merged**
