### PR TITLE
Get pages from article-number if pages not in fields_dict

### PR DESCRIPTION
**Pull request by gmatteo**
Some journals return the initial page number in article-number instead of pages.
This PR tries to fix this issue by looking for "article-number" if "pages" is not available.

### CODE REVIEW

**Comment by nschloe** [comment]
Interesting; I'll check it out tomorrow.

**Comment by gmatteo** [comment]
> the first one, https://doi.org/10.1103/physreve.74.06670, does not exist

Oops, it is https://doi.org/10.1103/PhysRevE.74.066704
(with 4 at the end)

> the second one, https://doi.org/10.1103/physrevb.92.125113, has article-number 125113 (see https://api.crossref.org/v1/works/http://dx.doi.org/10.1103/physrevb.92.125113) which hardly makes sense as a page range.

I agree that it's a bit weird but this is also what it reported in the bibtex entry automatically 
generated by the APS website

@article{PhysRevB.92.125113,
  title = {Two-component density functional theory within the projector augmented-wave approach: Accurate and self-consistent computations of positron lifetimes and momentum distributions},
  author = {Wiktor, Julia and Jomard, G\'erald and Torrent, Marc},
  journal = {Phys. Rev. B},
  volume = {92},
  issue = {12},
  pages = {125113},
  numpages = {15},
  year = {2015},
  month = {Sep},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevB.92.125113},
  url = {https://link.aps.org/doi/10.1103/PhysRevB.92.125113}
}

The journal uses 125133-1, 125113-2 etc to enumerate the pages of the article
and  without my modification the bibtex entry produced by betterbib-doi2bibtex 
does not contain the `pages` field

**Comment by nschloe** [comment]
> Oops, it is https://doi.org/10.1103/PhysRevE.74.066704

Alright. Pretty much the same situation there (https://api.crossref.org/v1/works/http://dx.doi.org/10.1103/physreve.74.066704).

> I agree that it's a bit weird but this is also what it reported in the bibtex entry automatically generated by the APS website

Yeah I mean, this just seems weird to me. Some bibtex styles render this as `pp. 125113`. If anything, the `article-number` should be listed as `eid` or something like that.

**Comment by leofang** [comment]
Found this issue from Google. Any chance this can get merged? It'll be useful for dealing with Phys Rev  series.

**Comment by nschloe** [comment]
> Any chance this can get merged?

I'm inclined not to merge it. It's just so weird. What does `pages = {125113}` even mean?

**Comment by leofang** [comment]
> > Any chance this can get merged?
> 
> I'm inclined not to merge it. It's just so weird. What does `pages = {125113}` even mean?

It wouldn't be that weird for physicists working with APS journals. We're just so used to having the `pages` there. 

If possible I'd suggest a middle ground: add a command line flag such as `-aps` or `-revtex` to turn on this behavior, and let the current behavior be the default. If @gmatteo lost the interest I can take over the PR and make a commit. Thanks.

**Comment by nschloe** [comment]
> If possible I'd suggest a middle ground: add a command line flag such as -aps

Agreed. Let's call it "--article-number-as-pages".

**Comment by nschloe** [comment]
Closing for lack of response. Feel free to open a new PR, I'll be happy to review again.

**Pull request closed without merging**
